blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('private/<int:pk>/', views.private, name='private'),
    path('add_private/<int:pk>', views.add_private, name='add_private'),
    path('look_article/<int:pk>', views.look_article, name='look_article'),
    path('look_user/<int:pk>', views.look_user, name='look_user'),
    path('logout/', views.logout, name='logout'),
    path('edit_article/<int:pk>', views.edit_article, name='edit_article'),
    path('send_message/<int:pk>', views.send_message, name='send_message'),
    path('check_message/<int:pk>', views.check_message, name='check_message'),
    path('check_one/<int:pk>', views.check_one, name='check_one'),
    path('add_file/<int:pk>', views.add_file, name='add_file'),
    path('check_files/<int:pk>', views.check_files, name='check_files'),
    path('check_file/<int:pk>', views.check_file, name='check_file'),
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    # path('chat/', include('chat.urls')),
]

blog/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:30] + '...'


class Message(models.Model):
    sender_id = models.IntegerField()
    msg = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.msg[:20] + '...'


class File(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import User, Article, Message, File
from django.http import HttpResponseRedirect, FileResponse
from django.urls import reverse
import os
# Create your views here.
PATH = os.getcwd()


def register(request):
    if request.method == 'POST':
        if request.POST['name'] and request.POST['password']:
            s = User(name=request.POST['name'], password=request.POST['password'])
            s.save()
            return HttpResponseRedirect(reverse('blog:private', args=(s.pk, )))
        return HttpResponseRedirect(reverse('blog:register', args=()))
    return render(request, 'blog/register.html')


def index(request):
    all_article = Article.objects.order_by('-pub_date')[:30]
    context = {
        'all_article': all_article,
        'not_is_login': not request.session.get('is_login'),
        'pk': request.session.get('user'),
    }
    return render(request, 'blog/index.html', context=context)


def login(request):
    if request.method == "POST":
        if request.POST['name'] and request.POST['password']:
            try:
                s = User.objects.get(name=request.POST['name'], password=request.POST['password'])
                request.session['is_login'] = True
                request.session['user'] = s.id
                print('You are success...')
                return HttpResponseRedirect(reverse('blog:private', args=(s.id, )))
            except (KeyError, User.DoesNotExist):
                print('failed..')
                return HttpResponseRedirect(reverse('blog:login', args=()))
    return render(request, 'blog/login.html')


def private(request, pk):
    if request.session.get('is_login') and request.session.get('user') == pk:
        s = get_object_or_404(User, pk=pk)
        all_article = s.article_set.order_by('-pub_date')
        context = {
            'user': s,
            'all_article': all_article,
        }
        return render(request, 'blog/private.html', context=context)
    print('enter failed...')
    return HttpResponseRedirect(reverse('blog:login', args=()))


def add_private(request, pk):
    if request.session.get('is_login') and request.session.get('user') == pk:
        user = get_object_or_404(User, pk=pk)
        context = {
            'user': user,
        }
        if request.method == 'POST':
            text = request.POST['text']
            user.article_set.create(text=text)
            return HttpResponseRedirect(reverse('blog:private', args=(pk, )))
        else:
            return render(request, 'blog/add_private.html', context=context)
    else:
        return render(request, 'blog/login.html')


def look_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article,
        'not_is_login': not request.session.get('is_login'),
        'pk': request.session.get('user'),
    }
    return render(request, 'blog/look_article.html', context=context)


def look_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    all_article = user.article_set.all()
    context = {
        'user': user,
        'not_is_login': not request.session.get('is_login'),
        'all_article': all_article,
        'pk': request.session.get('user'),
    }
    return render(request, 'blog/look_user.html', context=context)


def logout(request):
    request.session['is_login'] = False
    request.session['user'] = None
    return HttpResponseRedirect(reverse('blog:index', args=()))


def edit_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.session.get('is_login'):
        if article.user.pk == request.session.get('user'):
            if request.method == "POST":
                text = request.POST['text']
                article = get_object_or_404(Article, pk=pk)
                article.text = text
                article.save()
                return HttpResponseRedirect(reverse('blog:private', args=(article.user.pk, )))
            else:
                context = {
                    'article': article,
                }
                return render(request, 'blog/edit_article.html', context=context)
    return HttpResponseRedirect(reverse('blog:login', args=()))


def send_message(request, pk):
    if request.session.get('user') == pk and request.session.get('is_login'):
        context = {
            'pk': pk,
        }
        if request.method == 'POST':
            if request.POST['msg'] and request.POST['receiver_pk']:
                r = request.POST['receiver_pk']
                msg = request.POST['msg']
                receiver = get_object_or_404(User, pk=r)
                m = receiver.message_set.create(sender_id=pk, msg=msg)
                m.save()
                return HttpResponseRedirect(reverse('blog:private', args=(pk, )))
        return render(request, 'blog/send_message.html', context=context)
    return HttpResponseRedirect(reverse('blog:login', args=()))


def check_login(request, pk):
    return request.session.get('is_login') and request.session.get('user') == pk


def check_message(request, pk):
    user = get_object_or_404(User, pk=pk)
    unread_msg = user.message_set.filter(is_read=False)
    context = {
        'user': user,
        'unread_msg': unread_msg,
    }
    return render(request, 'blog/check_message.html', context=context)


def check_one(request, pk):
    msg = get_object_or_404(Message, pk=pk)
    if request.session.get('is_login') and request.session.get('user') == msg.receiver.pk:
        msg.is_read = True
        msg.save()
        context = {
            'msg': msg,
        }
        return render(request, 'blog/check_one.html', context=context)
    return HttpResponseRedirect(reverse('blog:login', args=()))


def add_file(request, pk):
    if check_login(request, pk):
        if request.method == 'POST':
            file = request.FILES.get('file')
            user = get_object_or_404(User, pk=int(request.POST.get('pk')))
            p = int(request.POST.get('pk'))
            if not file:
                return HttpResponseRedirect(reverse('blog:add_file', args=(pk, )))
            if not os.path.exists('files/' + str(p)):
                os.mkdir('files/' + str(p))
            with open('files/' + str(p) + '/' + file.name, 'wb+') as f:
                for i in file.chunks():
                    f.write(i)
            user.file_set.create(name=file)
            user.save()
            return HttpResponseRedirect(reverse('blog:private', args=(pk, )))
        context = {
            'pk': pk,
        }
        return render(request, 'blog/add_file.html', context=context)
    return HttpResponseRedirect(reverse('blog:login'))


def check_files(request, pk):
    if check_login(request, pk):
        user = get_object_or_404(User, pk=pk)
        all_file = user.file_set.all()
        context = {
            'all_file': all_file,
            'user': user,
        }
        return render(request, 'blog/check_files.html', context=context)
    return HttpResponseRedirect(reverse('blog:login'))


def check_file(request, pk):
    file = get_object_or_404(File, pk=pk)
    if check_login(request, file.user.pk):
        f = get_object_or_404(File, pk=pk)
        file = open(PATH + '/files/' + str(request.session.get('user')) + '/' + f.name, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="{filename}"'.format(filename=f.name)
        return response
    return HttpResponseRedirect(reverse('blog:login'))

blog/templates/blog/add_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
    <a href="{% url 'blog:index' %}">Index</a>   <a href="{% url 'blog:logout' %}">logout</a>
    <a href="{% url 'blog:private' pk %}">Home</a>
</div>
</nav>
<form  enctype="multipart/form-data" action="{% url 'blog:add_file' pk %}" method="post">
    {% csrf_token %}
    <input type="file" name="file">
    <br>
    <label>You want to send to:</label>
    <input type="text" name="pk"><br>
    <input type="submit" value="submit" class="btn btn-primary">
</form>
</body>
</html>

blog/templates/blog/add_private.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<a href="{% url 'blog:index' %}">Index</a><a href="{% url 'blog:private' user.id %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
<form action="{% url 'blog:add_private' user.id %}" method="post">
    {% csrf_token %}
    <textarea name="text" cols="200" rows="40"></textarea>
    <input type="submit" value="submit" class="btn btn-primary">
</form>
</body>
</html>

blog/templates/blog/check_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
<a href="{% url 'blog:index' %}">Index</a>   <a href="{% url 'blog:logout' %}">logout</a>
<a href="{% url 'blog:private' user.id %}">Home</a>
</div>
</nav>
<div class="container">
{% if all_file %}
{% for i in all_file %}
<p><a href="{% url 'blog:check_file' i.pk %}">{{ i.name }}</a></p>
{% endfor %}
{% else %}
<p>You have no file</p>
{% endif %}
</div>
</body>
</html>

blog/templates/blog/check_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
<a href="{% url 'blog:private' user.pk %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
</div>
</nav>
{% if unread_msg %}
{% for i in unread_msg %}
<div class="panel panel-default">
    <div class="panel-header">
    <label>Time:{{ i.date }}</label>
    <label>from:{{ i.sender_id }}</label>
    </div>
    <div class="panel-body">
    <p><a href="{% url 'blog:check_one' i.id %}">{{ i }}</a></p>
    </div>
</div>
{% endfor %}
{% else %}
<p>You have no unread message</p>
{% endif %}
</body>
</html>

blog/templates/blog/check_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
<a href="{% url 'blog:private' msg.receiver.pk %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
</div>
</nav>
<div class="panel panel-default">
    <div class="panel-heading">
    <label>Time:{{ msg.date }}</label>
    <label>From:{{ msg.sender_id }}</label>
    </div>
    <div class="panel-body">
        {{ msg.msg|linebreaks }}
    </div>
</div>
</body>
</html>

blog/templates/blog/edit_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
<a href="{% url 'blog:index' %}">Index</a>   <a href="{% url 'blog:private' article.user.id %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
</div>
</nav>
<form action="{% url 'blog:edit_article' article.pk %}" method="post">
    {% csrf_token %}
    <textarea name="text" cols="200" rows="40">
        {{ article.text }}
    </textarea>
    <input type="submit" value="submit" class="btn btn-primary">
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
{% if not_is_login %}
<a href="{% url 'blog:login' %}">Log in</a>
{% else %}
<a href="{% url 'blog:private' pk %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
{% endif %}
</div>
</nav>
{% for i in all_article %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
        <p><a href="{% url 'blog:look_article' i.id %}">time: {{ i.pub_date }} user: {{ i.user.name }}</a></p>
        </div>
        <div class="panel-body">
            {{ i.text|linebreaks }}
        </div>
    </div>
</div>
{% endfor %}
</body>
</html>

blog/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<div class="container">
<h1 class="form-signin-heading">Log in</h1>
</div>
<div class="container">
<a href="{% url 'blog:index' %}">Index</a> <a href="{% url 'blog:register' %}">Don't have one?Register</a>
</div>
<div class="container">
<form action="{% url 'blog:login' %}" method="post">
    {% csrf_token %}
    <label>name:</label><p><input type="text" name="name"></p>
    <label>password:</label><p><input type="password" name="password"></p>
    {% buttons %}
    <input type="submit" value="submit" class="btn btn-primary">
    {% endbuttons %}
</form>
</div>
</body>
</html>

blog/templates/blog/look_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
{% if not_is_login %}
<a href="{% url 'blog:login' %}">Log in</a>
{% else %}
<a href="{% url 'blog:private' pk %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
{% endif %}
<a href="{% url 'blog:index' %}">Index</a>
<a href="{% url 'blog:look_user' article.user.id %}">{{ article.user.name }}</a>
</div>
</nav>
<p>
    {{ article.text }}
</p>
<p>
    time:{{ article.pub_date }}
</p>
</body>
</html>

blog/templates/blog/look_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
{% if not_is_login %}
<a href="{% url 'blog:login' %}">Log in</a>
{% else %}
<a href="{% url 'blog:private' pk %}">Home</a>
<a href="{% url 'blog:logout' %}">logout</a>
{% endif %}
<a href="{% url 'blog:index' %}">Index</a>
<label>{{ user.name }}</label>
<div class="panel panel-default">
    {% for i in all_article %}
    <div class="panel-heading">
        <h3>time:{{ i.pub_date }}</h3>
    </div>
    <div class="panel-body">
        {{ i.text|linebreaks }}
    </div>
    {% endfor %}
</div>
</body>
</html>

blog/templates/blog/private.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
<a href="{% url 'blog:index' %}">Index</a>   <a href="{% url 'blog:logout' %}">logout</a>
</div>
</nav>
<div class="container">
<h1>{{ user.name }}</h1>
</div>
<div class="container">
{% if all_article %}
{% for i in all_article %}
    <div class="panel panel-default">
    <div class="panel-heading">
        <label>  Time:  {{ i.pub_date }}</label><a href="{% url 'blog:edit_article' i.pk %}">Edit it</a>
    </div>
    <div class="panel-body">
         {{ i.text|linebreaks }}
    </div>
    </div>
{% endfor %}
{% else %}
<p>You have no article!</p>
{% endif %}
</div>
<div class="container">
<p><a href="{% url 'blog:add_private' user.id %}">Add your article</a></p>
<p><a href="{% url 'blog:send_message' user.id %}">Send your message</a></p>
<p><a href="{% url 'blog:check_message' user.id %}">Check your messages</a></p>
<p><a href="{% url 'blog:add_file' user.id %}">Add file</a></p>
<p><a href="{% url 'blog:check_files' user.id %}">Check your file</a></p>
</div>
</body>
</html>

blog/templates/blog/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<h1>Register</h1>
<a href="{% url 'blog:index' %}">Index</a>
<form action="{% url 'blog:register' %}" method="post">
    {% csrf_token %}
    <label>name</label><p><input type="text" name="name"></p>
    <label>password</label><p><input type="text" name="password"></p>
    <input type="submit" value="submit" class="btn btn-primary">
</form>
</body>
</html>

blog/templates/blog/send_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link href="https://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-header">
    <a href="{% url 'blog:index' %}">Index</a>   <a href="{% url 'blog:logout' %}">logout</a>
    <a href="{% url 'blog:private' pk %}">Home</a>
</div>
</nav>
<form action="{% url 'blog:send_message' pk %}" method="post">
    {% csrf_token %}
    <textarea name="msg" cols="200" rows="30"></textarea>
    <label>You want to send to:</label><input type="text" name="receiver_pk">
    <input type="submit" value="submit" class="btn btn-primary">
</form>
</body>
</html>